export type Depth = "light" | "honest" | "deep" | "prayerful";

export const DEPTHS: Record<Depth, { label: string; tag: string; color: string; glyph: string }> = {
  light:     { label: "Light",     tag: "Warm, low-risk",        color: "var(--sp-amber)",  glyph: "✶" },
  honest:    { label: "Honest",    tag: "Reflective, personal",  color: "var(--sp-rose)",   glyph: "◉" },
  deep:      { label: "Deep",      tag: "Vulnerable, growth",    color: "var(--sp-indigo)", glyph: "❖" },
  prayerful: { label: "Prayerful", tag: "Faith-shaped, optional",color: "var(--sp-sage)",   glyph: "✦" },
};

export const DECKS: Record<Depth, string[]> = {
  light: [
    "What small thing made your week better?",
    "What is something you used to love as a child?",
    "What is one simple joy you think more people overlook?",
    "What's a song that's been stuck in your head lately?",
    "What's the last thing that made you genuinely laugh?",
    "If you had a free Saturday, no obligations, what would you do?",
    "What's a tiny ritual you secretly enjoy?",
    "What's a meal that always feels like home?",
    "What's something you're looking forward to this month?",
    "What's a compliment you've received that's stuck with you?",
    "What show or book are you slowly working through?",
    "What's a smell that instantly calms you?",
    "If your week had a soundtrack, what would the opening track be?",
    "What's a small win you're proud of recently?",
    "What's the most underrated everyday pleasure?",
    "What's a place you keep meaning to revisit?",
    "What's something you're curious about right now?",
    "What hobby would you pick up if time were free?",
    "What's a kindness someone showed you this week?",
    "What's the best thing within arm's reach right now?",
  ],
  honest: [
    "What's something you've been carrying quietly?",
    "Where have you felt misunderstood recently?",
    "What is one area of your life where you want more courage?",
    "What's a truth you've been avoiding saying out loud?",
    "Where are you pretending more than you'd like to admit?",
    "What's been draining you that you haven't named yet?",
    "When did you last feel truly seen?",
    "What's a season of life you're still processing?",
    "What's something you want to forgive yourself for?",
    "Who do you owe a real conversation to?",
    "What's an opinion you've quietly changed your mind about?",
    "What part of your story do you usually skip when introducing yourself?",
    "Where do you feel the gap between who you are and who you want to be?",
    "What does rest actually look like for you right now?",
    "What's something you wish someone would ask you?",
    "What's a fear you've been working through quietly?",
    "What does belonging feel like for you these days?",
    "Where in your life are you craving more honesty?",
    "What's been weighing on you that feels too small to mention?",
    "What's one thing you're learning to be patient with?",
  ],
  deep: [
    "What part of you do you wish people saw more clearly?",
    "What are you learning to let go of?",
    "What kind of person are you becoming?",
    "What would you regret never saying?",
    "What is the lie you most often tell yourself?",
    "Where do you sense you are being shaped right now?",
    "What's a wound that's quietly informing your decisions?",
    "What would change if you trusted yourself more?",
    "What does love require of you in this season?",
    "Whose voice do you hear loudest when you are afraid?",
    "What is your relationship with silence?",
    "What old belief no longer fits the person you're becoming?",
    "What does your future self want you to know today?",
    "Where have you been brave in a way no one noticed?",
    "What truth feels too big to hold alone?",
    "What is one thing you'd want said about your life?",
    "What part of yourself do you most want to integrate?",
    "What do you grieve that you've never given language to?",
    "Where do you feel God, the universe, or life inviting you deeper?",
    "What story about yourself are you ready to release?",
  ],
  prayerful: [
    "Where have you seen grace recently?",
    "What is one prayer you don't know how to say yet?",
    "What is God teaching you in this season?",
    "Where do you most need peace right now?",
    "What are you grateful for that you usually overlook?",
    "Who comes to mind when you ask, 'who needs prayer today?'",
    "What burden are you ready to set down?",
    "Where do you sense an invitation to trust?",
    "What truth about yourself do you most need to hear?",
    "What feels heavy that you'd like to hand over?",
    "Where have you felt held this week?",
    "What is one thing you want to offer in thanks?",
    "Where are you being asked to be still?",
    "What does hope look like for you right now?",
    "Where do you long to be made new?",
    "What are you ready to forgive — in yourself or another?",
    "What's a small mercy you noticed today?",
    "Where do you sense love meeting you in your weakness?",
    "What is a question you'd rather sit with than solve?",
    "What are you asking for, even quietly?",
  ],
};

export function pickPrompt(depth: Depth, exclude: string[] = []): string {
  const pool = DECKS[depth].filter((p) => !exclude.includes(p));
  const list = pool.length ? pool : DECKS[depth];
  return list[Math.floor(Math.random() * list.length)];
}
