/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecapLocalRouteImport } from './routes/recap.local'
import { Route as PlaySoloRouteImport } from './routes/play.solo'
import { Route as PlayLocalRouteImport } from './routes/play.local'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapLocalRoute = RecapLocalRouteImport.update({
  id: '/recap/local',
  path: '/recap/local',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySoloRoute = PlaySoloRouteImport.update({
  id: '/play/solo',
  path: '/play/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/play/local',
  path: '/play/local',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/play/local': typeof PlayLocalRoute
  '/play/solo': typeof PlaySoloRoute
  '/recap/local': typeof RecapLocalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/play/local': typeof PlayLocalRoute
  '/play/solo': typeof PlaySoloRoute
  '/recap/local': typeof RecapLocalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/play/local': typeof PlayLocalRoute
  '/play/solo': typeof PlaySoloRoute
  '/recap/local': typeof RecapLocalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/join' | '/play/local' | '/play/solo' | '/recap/local'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/join' | '/play/local' | '/play/solo' | '/recap/local'
  id: '__root__' | '/' | '/join' | '/play/local' | '/play/solo' | '/recap/local'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  PlayLocalRoute: typeof PlayLocalRoute
  PlaySoloRoute: typeof PlaySoloRoute
  RecapLocalRoute: typeof RecapLocalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/local': {
      id: '/recap/local'
      path: '/recap/local'
      fullPath: '/recap/local'
      preLoaderRoute: typeof RecapLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/solo': {
      id: '/play/solo'
      path: '/play/solo'
      fullPath: '/play/solo'
      preLoaderRoute: typeof PlaySoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/local': {
      id: '/play/local'
      path: '/play/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  PlayLocalRoute: PlayLocalRoute,
  PlaySoloRoute: PlaySoloRoute,
  RecapLocalRoute: RecapLocalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
