/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SparksRouteImport } from './routes/sparks'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareIdRouteImport } from './routes/share.$id'
import { Route as RoomNewRouteImport } from './routes/room.new'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as RecapLocalRouteImport } from './routes/recap.local'
import { Route as RecapIdRouteImport } from './routes/recap.$id'
import { Route as PlaySoloRouteImport } from './routes/play.solo'
import { Route as PlayLocalRouteImport } from './routes/play.local'
import { Route as AsyncNewRouteImport } from './routes/async.new'
import { Route as AsyncIdRouteImport } from './routes/async.$id'

const SparksRoute = SparksRouteImport.update({
  id: '/sparks',
  path: '/sparks',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIdRoute = ShareIdRouteImport.update({
  id: '/share/$id',
  path: '/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomNewRoute = RoomNewRouteImport.update({
  id: '/room/new',
  path: '/room/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapLocalRoute = RecapLocalRouteImport.update({
  id: '/recap/local',
  path: '/recap/local',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapIdRoute = RecapIdRouteImport.update({
  id: '/recap/$id',
  path: '/recap/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySoloRoute = PlaySoloRouteImport.update({
  id: '/play/solo',
  path: '/play/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/play/local',
  path: '/play/local',
  getParentRoute: () => rootRouteImport,
} as any)
const AsyncNewRoute = AsyncNewRouteImport.update({
  id: '/async/new',
  path: '/async/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AsyncIdRoute = AsyncIdRouteImport.update({
  id: '/async/$id',
  path: '/async/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/sparks': typeof SparksRoute
  '/async/$id': typeof AsyncIdRoute
  '/async/new': typeof AsyncNewRoute
  '/play/local': typeof PlayLocalRoute
  '/play/solo': typeof PlaySoloRoute
  '/recap/$id': typeof RecapIdRoute
  '/recap/local': typeof RecapLocalRoute
  '/room/$code': typeof RoomCodeRoute
  '/room/new': typeof RoomNewRoute
  '/share/$id': typeof ShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/sparks': typeof SparksRoute
  '/async/$id': typeof AsyncIdRoute
  '/async/new': typeof AsyncNewRoute
  '/play/local': typeof PlayLocalRoute
  '/play/solo': typeof PlaySoloRoute
  '/recap/$id': typeof RecapIdRoute
  '/recap/local': typeof RecapLocalRoute
  '/room/$code': typeof RoomCodeRoute
  '/room/new': typeof RoomNewRoute
  '/share/$id': typeof ShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/join': typeof JoinRoute
  '/sparks': typeof SparksRoute
  '/async/$id': typeof AsyncIdRoute
  '/async/new': typeof AsyncNewRoute
  '/play/local': typeof PlayLocalRoute
  '/play/solo': typeof PlaySoloRoute
  '/recap/$id': typeof RecapIdRoute
  '/recap/local': typeof RecapLocalRoute
  '/room/$code': typeof RoomCodeRoute
  '/room/new': typeof RoomNewRoute
  '/share/$id': typeof ShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/join'
    | '/sparks'
    | '/async/$id'
    | '/async/new'
    | '/play/local'
    | '/play/solo'
    | '/recap/$id'
    | '/recap/local'
    | '/room/$code'
    | '/room/new'
    | '/share/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/join'
    | '/sparks'
    | '/async/$id'
    | '/async/new'
    | '/play/local'
    | '/play/solo'
    | '/recap/$id'
    | '/recap/local'
    | '/room/$code'
    | '/room/new'
    | '/share/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/join'
    | '/sparks'
    | '/async/$id'
    | '/async/new'
    | '/play/local'
    | '/play/solo'
    | '/recap/$id'
    | '/recap/local'
    | '/room/$code'
    | '/room/new'
    | '/share/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  JoinRoute: typeof JoinRoute
  SparksRoute: typeof SparksRoute
  AsyncIdRoute: typeof AsyncIdRoute
  AsyncNewRoute: typeof AsyncNewRoute
  PlayLocalRoute: typeof PlayLocalRoute
  PlaySoloRoute: typeof PlaySoloRoute
  RecapIdRoute: typeof RecapIdRoute
  RecapLocalRoute: typeof RecapLocalRoute
  RoomCodeRoute: typeof RoomCodeRoute
  RoomNewRoute: typeof RoomNewRoute
  ShareIdRoute: typeof ShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sparks': {
      id: '/sparks'
      path: '/sparks'
      fullPath: '/sparks'
      preLoaderRoute: typeof SparksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$id': {
      id: '/share/$id'
      path: '/share/$id'
      fullPath: '/share/$id'
      preLoaderRoute: typeof ShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/new': {
      id: '/room/new'
      path: '/room/new'
      fullPath: '/room/new'
      preLoaderRoute: typeof RoomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/local': {
      id: '/recap/local'
      path: '/recap/local'
      fullPath: '/recap/local'
      preLoaderRoute: typeof RecapLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$id': {
      id: '/recap/$id'
      path: '/recap/$id'
      fullPath: '/recap/$id'
      preLoaderRoute: typeof RecapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/solo': {
      id: '/play/solo'
      path: '/play/solo'
      fullPath: '/play/solo'
      preLoaderRoute: typeof PlaySoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/local': {
      id: '/play/local'
      path: '/play/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/async/new': {
      id: '/async/new'
      path: '/async/new'
      fullPath: '/async/new'
      preLoaderRoute: typeof AsyncNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/async/$id': {
      id: '/async/$id'
      path: '/async/$id'
      fullPath: '/async/$id'
      preLoaderRoute: typeof AsyncIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  JoinRoute: JoinRoute,
  SparksRoute: SparksRoute,
  AsyncIdRoute: AsyncIdRoute,
  AsyncNewRoute: AsyncNewRoute,
  PlayLocalRoute: PlayLocalRoute,
  PlaySoloRoute: PlaySoloRoute,
  RecapIdRoute: RecapIdRoute,
  RecapLocalRoute: RecapLocalRoute,
  RoomCodeRoute: RoomCodeRoute,
  RoomNewRoute: RoomNewRoute,
  ShareIdRoute: ShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
